// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RealEstateProject.Models;

#nullable disable

namespace RealEstateProject.Migrations
{
    [DbContext(typeof(RealEstateProjectContext))]
    [Migration("20260513132244_FreshSync")]
    partial class FreshSync
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RealEstateProject.Models.AdminCommission", b =>
                {
                    b.Property<int>("CommissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("commission_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommissionId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<int>("TransectionId")
                        .HasColumnType("int")
                        .HasColumnName("transectionId");

                    b.HasKey("CommissionId");

                    b.HasIndex("TransectionId");

                    b.ToTable("Admin_commission", (string)null);
                });

            modelBuilder.Entity("RealEstateProject.Models.Amenity", b =>
                {
                    b.Property<int>("AmenityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("amenityId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AmenityId"));

                    b.Property<string>("AmenityName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("amenity_name");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.HasKey("AmenityId");

                    b.ToTable("Amenity", (string)null);
                });

            modelBuilder.Entity("RealEstateProject.Models.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.HasKey("CityId");

                    b.HasIndex("StateId");

                    b.ToTable("City", (string)null);
                });

            modelBuilder.Entity("RealEstateProject.Models.ContactSeller", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("contactId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactId"));

                    b.Property<byte[]>("ContactDate")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("contact_date");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int")
                        .HasColumnName("propertyId");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ContactId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("UserId");

                    b.ToTable("Contact_Seller", (string)null);
                });

            modelBuilder.Entity("RealEstateProject.Models.Enquiry", b =>
                {
                    b.Property<int>("EnquiryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnquiryId"));

                    b.Property<decimal?>("AdminCommission")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AgreementChargesAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BrokerageChargesAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CommissionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("DocumentPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("FirstMonthRentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsAdminApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAgreementChargesPaid")
                        .HasColumnType("bit");

                    b.Property<bool>("IsApprovedByOwner")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBrokeragePaid")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBuyerPaid")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCommissionPaid")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCommissionPaidByBuyer")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCommissionPaidByOwner")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDealApprovedByAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDocumentApprovedByAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDocumentUploaded")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDocumentVerified")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFirstMonthRentPaid")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMeetingDone")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMonthlyRentPaid")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOwnerPaid")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRegistered")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSecurityDepositPaid")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTokenPaid")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTokenPaidByBuyer")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTokenPaidByOwner")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MonthlyRentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("OwnerUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PreferredVisitDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PreferredVisitTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PropertyId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PropertyPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RazorpayOrderId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazorpayPaymentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SecurityDepositAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SenderUserId")
                        .HasColumnType("int");

                    b.Property<int?>("Stage")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TokenAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VisitStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EnquiryId")
                        .HasName("PK__Enquirie__0A019B7D4E4AF15A");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("SenderUserId");

                    b.ToTable("Enquiries");
                });

            modelBuilder.Entity("RealEstateProject.Models.Favorite", b =>
                {
                    b.Property<int>("FavoriteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("favoriteId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FavoriteId"));

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("FavoriteId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("UserId");

                    b.ToTable("Favorite", (string)null);
                });

            modelBuilder.Entity("RealEstateProject.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("EnquiryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Info");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("NotificationId");

                    b.HasIndex("EnquiryId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("RealEstateProject.Models.Property", b =>
                {
                    b.Property<int>("ProperyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProperyId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<int>("AreaSqft")
                        .HasColumnType("int")
                        .HasColumnName("area_sqft");

                    b.Property<int>("Bathrooms")
                        .HasColumnType("int")
                        .HasColumnName("bathrooms");

                    b.Property<int>("Bedroom")
                        .HasColumnType("int")
                        .HasColumnName("bedroom");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Furnishing")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("furnishing");

                    b.Property<string>("Pincode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("pincode");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("price");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("property_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("title");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProperyId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CityId");

                    b.HasIndex("UserId");

                    b.ToTable("Property", (string)null);
                });

            modelBuilder.Entity("RealEstateProject.Models.PropertyAmenity", b =>
                {
                    b.Property<int>("ProperyAmenityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Propery_amenity_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProperyAmenityId"));

                    b.Property<int>("AmenityId")
                        .HasColumnType("int")
                        .HasColumnName("amenityId");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.HasKey("ProperyAmenityId");

                    b.HasIndex("AmenityId");

                    b.HasIndex("PropertyId");

                    b.ToTable("Property_amenity", (string)null);
                });

            modelBuilder.Entity("RealEstateProject.Models.PropertyCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("CategoryId");

                    b.ToTable("Property_Categories", (string)null);
                });

            modelBuilder.Entity("RealEstateProject.Models.ProperyImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.HasKey("ImageId")
                        .HasName("PK__Propery___7516F70CBBA8697E");

                    b.HasIndex("PropertyId");

                    b.ToTable("Propery_Image", (string)null);
                });

            modelBuilder.Entity("RealEstateProject.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("reviewId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<byte[]>("CreatedAt")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("created_at");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ReviewId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("RealEstateProject.Models.State", b =>
                {
                    b.Property<int>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StateId"));

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("StateId");

                    b.ToTable("States");
                });

            modelBuilder.Entity("RealEstateProject.Models.Transection", b =>
                {
                    b.Property<int>("TransectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransectionId"));

                    b.Property<decimal>("CommissionAmount")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("commission_amount");

                    b.Property<decimal>("CommissionPercentage")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("commission_percentage");

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("final_price");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TransactionDate")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("TransactionDate");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TransectionId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("UserId");

                    b.ToTable("Transection", (string)null);
                });

            modelBuilder.Entity("RealEstateProject.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Created_at")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("ProfileImage")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("RealEstateProject.Models.AdminCommission", b =>
                {
                    b.HasOne("RealEstateProject.Models.Transection", "Transection")
                        .WithMany("AdminCommissions")
                        .HasForeignKey("TransectionId")
                        .IsRequired()
                        .HasConstraintName("FK_Admin_commission_Transection");

                    b.Navigation("Transection");
                });

            modelBuilder.Entity("RealEstateProject.Models.City", b =>
                {
                    b.HasOne("RealEstateProject.Models.State", "State")
                        .WithMany("Cities")
                        .HasForeignKey("StateId")
                        .IsRequired()
                        .HasConstraintName("FK_City_States");

                    b.Navigation("State");
                });

            modelBuilder.Entity("RealEstateProject.Models.ContactSeller", b =>
                {
                    b.HasOne("RealEstateProject.Models.Property", "Property")
                        .WithMany("ContactSellers")
                        .HasForeignKey("PropertyId")
                        .IsRequired()
                        .HasConstraintName("FK_Contact_Seller_Property");

                    b.HasOne("RealEstateProject.Models.User", "User")
                        .WithMany("ContactSellers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Contact_Seller_User");

                    b.Navigation("Property");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RealEstateProject.Models.Enquiry", b =>
                {
                    b.HasOne("RealEstateProject.Models.User", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("OwnerUserId");

                    b.HasOne("RealEstateProject.Models.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId");

                    b.HasOne("RealEstateProject.Models.User", "SenderUser")
                        .WithMany()
                        .HasForeignKey("SenderUserId");

                    b.Navigation("OwnerUser");

                    b.Navigation("Property");

                    b.Navigation("SenderUser");
                });

            modelBuilder.Entity("RealEstateProject.Models.Favorite", b =>
                {
                    b.HasOne("RealEstateProject.Models.Property", "Property")
                        .WithMany("Favorites")
                        .HasForeignKey("PropertyId")
                        .IsRequired()
                        .HasConstraintName("FK_Favorite_Property");

                    b.HasOne("RealEstateProject.Models.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Favorite_User");

                    b.Navigation("Property");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RealEstateProject.Models.Notification", b =>
                {
                    b.HasOne("RealEstateProject.Models.Enquiry", "Enquiry")
                        .WithMany("Notifications")
                        .HasForeignKey("EnquiryId")
                        .HasConstraintName("FK_Notifications_Enquiries");

                    b.HasOne("RealEstateProject.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Notifications_User");

                    b.Navigation("Enquiry");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RealEstateProject.Models.Property", b =>
                {
                    b.HasOne("RealEstateProject.Models.PropertyCategory", "Category")
                        .WithMany("Properties")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_Property_Property_Categories");

                    b.HasOne("RealEstateProject.Models.City", "City")
                        .WithMany("Properties")
                        .HasForeignKey("CityId")
                        .IsRequired()
                        .HasConstraintName("FK_Property_City");

                    b.HasOne("RealEstateProject.Models.User", "User")
                        .WithMany("Properties")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Property_User");

                    b.Navigation("Category");

                    b.Navigation("City");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RealEstateProject.Models.PropertyAmenity", b =>
                {
                    b.HasOne("RealEstateProject.Models.Amenity", "Amenity")
                        .WithMany("PropertyAmenities")
                        .HasForeignKey("AmenityId")
                        .IsRequired()
                        .HasConstraintName("FK_Property_amenity_Amenity");

                    b.HasOne("RealEstateProject.Models.Property", "Property")
                        .WithMany("PropertyAmenities")
                        .HasForeignKey("PropertyId")
                        .IsRequired()
                        .HasConstraintName("FK_Property_amenity_Property");

                    b.Navigation("Amenity");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("RealEstateProject.Models.ProperyImage", b =>
                {
                    b.HasOne("RealEstateProject.Models.Property", "Property")
                        .WithMany("ProperyImages")
                        .HasForeignKey("PropertyId")
                        .IsRequired()
                        .HasConstraintName("FK__Propery_I__Prope__29221CFB");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("RealEstateProject.Models.Review", b =>
                {
                    b.HasOne("RealEstateProject.Models.Property", "Property")
                        .WithMany("Reviews")
                        .HasForeignKey("PropertyId")
                        .IsRequired()
                        .HasConstraintName("FK_Reviews_Property");

                    b.HasOne("RealEstateProject.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Reviews_User");

                    b.Navigation("Property");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RealEstateProject.Models.Transection", b =>
                {
                    b.HasOne("RealEstateProject.Models.Property", "Property")
                        .WithMany("Transections")
                        .HasForeignKey("PropertyId")
                        .IsRequired()
                        .HasConstraintName("FK_Transection_Property");

                    b.HasOne("RealEstateProject.Models.User", "User")
                        .WithMany("Transections")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Transection_User");

                    b.Navigation("Property");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RealEstateProject.Models.Amenity", b =>
                {
                    b.Navigation("PropertyAmenities");
                });

            modelBuilder.Entity("RealEstateProject.Models.City", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("RealEstateProject.Models.Enquiry", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("RealEstateProject.Models.Property", b =>
                {
                    b.Navigation("ContactSellers");

                    b.Navigation("Favorites");

                    b.Navigation("PropertyAmenities");

                    b.Navigation("ProperyImages");

                    b.Navigation("Reviews");

                    b.Navigation("Transections");
                });

            modelBuilder.Entity("RealEstateProject.Models.PropertyCategory", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("RealEstateProject.Models.State", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("RealEstateProject.Models.Transection", b =>
                {
                    b.Navigation("AdminCommissions");
                });

            modelBuilder.Entity("RealEstateProject.Models.User", b =>
                {
                    b.Navigation("ContactSellers");

                    b.Navigation("Favorites");

                    b.Navigation("Notifications");

                    b.Navigation("Properties");

                    b.Navigation("Reviews");

                    b.Navigation("Transections");
                });
#pragma warning restore 612, 618
        }
    }
}
